# 这是一个参数配置文件
Initialize: # 初始化的参数
  # -------------------归一化参数设置-----------------------------#
  # -------------归一化默认参数取值为（0-1）------------------------#
  A_NORMAL : 0
  B_NORMAL : 1
  # -------------------动作个数和状态个数--------------------------#
  ACTION_NUM: 30 # 动作空间个数
  STATE_NUM: 30  # 状态空间个数
  # ---------------------奖励函数参数的权重值--------------------------#
  BETA1 : 0.7  # free_bw 剩余带宽的权重值
  BETA2 : 0.3  # delay 时延的权重值
  BETA3 : 0.1  # loss 权重值
  BETA4 : 0.1  # packet drop 权重值
  BETA5 : 0.1  # distance 权重值
  # --------------------奖励函数惩罚值---------------------------#
  DISCOUNT1 : -0.5  # 回路惩罚值  # -0.5
  DISCOUNT2 : -0.8  # 不是边的惩罚值 # -0.8
SOURCE_DESTINATION:
  - !!python/tuple [ 1, 8 ] # 起点-终点
  - !!python/tuple [ 8, 19 ]
#  - !!python/tuple [ 19, 29 ]

Train: # 训练时候的参数
  # ---------------强化学习训练使用的参数------------------------#
  EPOCH: 1000 # 迭代次数
  CLIP_PARAM: 0.2 # clip的参数
  PPO_UPDATE_TIME: 5 # PPO 网络参数更新时间
  BACH_SIZE: 32 # 批量大小
  ACTOR_LR: 1e-3 # 动作网络的学习率
  CRITIC_LR: 3e-3 # 策略网络的学习率

  GAMMA : 0.99  # 折扣率的大小
  TAU : 0.001  # 参数更新的权重值
  MAX_EPISODES : 100  # 迭代的次数
  MAX_STEPS : 1000  # 最大的步长

