# 这是一个参数配置文件
Initialize: # 初始化的参数
  # -------------------归一化参数设置-----------------------------#
  # -------------归一化默认参数取值为（0-1）------------------------#
  A_NORMAL: 0  # 左边界的值
  B_NORMAL: 1  # 右边界的值
  # -------------------动作个数和状态个数--------------------------#
  ACTION_NUM: 30 # 动作空间个数
  STATE_NUM: 30  # 状态空间个数
  # ---------------------奖励函数参数的权重值--------------------------#
  BETA1: 0.9  # free_bw 剩余带宽的权重值
  BETA2: 0.4  # delay 时延的权重值
  BETA3: 0.4  # loss 权重值
  BETA4: 0.3  # packet drop 权重值
  BETA5: 0.2  # distance 权重值
  # --------------------奖励函数惩罚值---------------------------#
  DISCOUNT1: -0.5  # 回路惩罚值  # -0.5
  DISCOUNT2: -0.8  # 不是边的惩罚值 # -0.8
  #---------------------每个域最后一个交换机的标号，用于区分域与域之间的信息-------------#
  DOMAIN_END_NODE1: 10 # 第一个域最终的交换机节点，例如1-10为第一子域
  DOMAIN_END_NODE2: 20
  DOMAIN_END_NODE3: 30
# ----------------------训练开始的起点-终点---------------------------#
# Set source and destination nodes
SOURCE_DESTINATION:
  - !!python/tuple [ 1, 29 ] # 起点-终点
# --------------------------网络故障节点和网络故障链路设置-----------------------------#
NODES_FAULT:
  - 6 # 故障节点
EDGES_FAULT:
  - !!python/tuple [ 2, 5 ] # 故障边
  - !!python/tuple [ 3, 9 ]
# ----------------------域间链路信息---------------------------#
# !!python/tuple 在yaml中解释为元组，不会自动解释成字符串
DOMAIN_LINKS:
  - !!python/tuple [ 10, 16 ]
  - !!python/tuple [ 8, 11 ]
  - !!python/tuple [ 7, 12 ]
  - !!python/tuple [ 17, 21 ]
  - !!python/tuple [ 17, 22 ]
  - !!python/tuple [ 18, 22 ]
  - !!python/tuple [ 18, 23 ]
  - !!python/tuple [ 19, 23 ]
  - !!python/tuple [ 19, 24 ]
  - !!python/tuple [ 20, 24 ]

Train: # 训练时候的参数
  # ---------------强化学习训练使用的参数------------------------#
  EPOCH: 200 # 迭代次数
  CLIP_PARAM: 0.2 # clip的参数
  PPO_UPDATE_TIME: 5 # PPO 网络参数更新时间
  BACH_SIZE: 32 # 批量大小
  ACTOR_LR: 1e-3 # 动作网络的学习率
  CRITIC_LR: 3e-3 # 策略网络的学习率

  GAMMA: 0.99  # 折扣率的大小
  TAU: 0.001  # 参数更新的权重值
  MAX_EPISODES: 100  # 迭代的次数
  MAX_STEPS: 1000  # 最大的步长

